release: python manage.py migrate --noinput
web: python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'njd07')" && gunicorn visualizer_api.wsgi --log-file - --bind 0.0.0.0:8080
